getwd()
source('~/Dropbox/tatone_j/1_ffq-single-food-process.R')

food_items <- 
  c("id_spd",
    "oil_spd",
    "o_spd",
    "rapeseed_spd",
    "c_spd",
    "soy.90_spd",
    "veg.oil_spd",
    "multvit_spd",
    "mulfrq_spd",
    "q1bpt_spd",
    "centrum.silver_spd",
    "theragran.m_spd",
    "centrum_spd",
    "oneaday.essent_spd",
    "other.mv_spd",
    "brndpt_spd",
    "mulbrnd_spd",
    "vipt_spd",
    "vitamin.a_spd",
    "ad_spd",
    "k.supp_spd",
    "kd_spd",
    "vitamin.c_spd",
    "cd_spd",
    "b6_spd",
    "b6d_spd",
    "vitamin.e_spd",
    "ed_spd",
    "etype_spd",
    "calcium_spd",
    "cad_spd",
    "sel_spd",
    "seld_spd",
    "vitamin.d_spd",
    "vitdd_spd",
    "zinc_spd",
    "znd_spd",
    "otherptb_spd",
    "metamucil_spd",
    "cod.liv.oil_spd",
    "b12_spd",
    "linseed_spd",
    "flax_spd",
    "bcar_spd",
    "magnesium_spd",
    "omega.3.epa_spd",
    "niacin2_spd",
    "cr_spd",
    "lecithin_spd",
    "coq10_spd",
    "chol_spd",
    "folic.acid_spd",
    "bcompl_spd",
    "lyco_spd",
    "dhea_spd",
    "iron_spd",
    "others_spd",
    "sugpt_spd",
    "sug_spd",
    "cerpt_spd",
    "cer_spd",
    "margptb_spd",
    "mn_spd",
    "ms_spd",
    "mt_spd",
    "msp_spd",
    "msq_spd",
    "mfpt_spd",
    "mreg_spd",
    "mlt_spd",
    "mnf_spd",
    "mtpt_spd",
    "mbpt_spd",
    "mb_spd",
    "dpt_spd",
    "skim.kids_spd",
    "milk2_spd",
    "milk_spd",
    "soymilk.fort_spd",
    "cream_spd",
    "cof.wht_spd",
    "yogurt.froz_spd",
    "ice.cr_spd",
    "yog.plain_spd",
    "yog_spd",
    "margarine_spd",
    "bu_spd",
    "cot.ch_spd",
    "cr.ch_spd",
    "oth.ch_spd",
    "ch.soy_spd",
    "ch.reg_spd",
    "ch.lofat_spd",
    "ch.nofat_spd",
    "ch.none_spd",
    "ch.pt_spd",
    "fpt_spd",
    "raisgrp_spd",
    "prun_spd",
    "prun.j_spd",
    "ban_spd",
    "cant_spd",
    "avocado_spd",
    "apple_spd",
    "a.j_spd",
    "orang_spd",
    "o.j.calc_spd",
    "o.j_spd",
    "grfrt_spd",
    "oth.f.j_spd",
    "straw_spd",
    "blue_spd",
    "peaches_spd",
    "apricot_spd",
    "vpt_spd",
    "tom_spd",
    "tom.j_spd",
    "tom.s_spd",
    "salsa_spd",
    "st.beans_spd",
    "beans_spd",
    "tofu_spd",
    "peas_spd",
    "broc_spd",
    "caul_spd",
    "cabb_spd",
    "brusl_spd",
    "carrot.r_spd",
    "carrot.c_spd",
    "corn_spd",
    "mix.veg_spd",
    "swt.pot_spd",
    "yel.sqs_spd",
    "zuke_spd",
    "kale_spd",
    "spin.ckd_spd",
    "spin.raw_spd",
    "ice.let_spd",
    "rom.let_spd",
    "celery_spd",
    "peppers_spd",
    "onions_spd",
    "onions1_spd",
    "meatpt_spd",
    "eggs.omega_spd",
    "eggs_spd",
    "hotdog_spd",
    "chix.dog_spd",
    "chix.sand_spd",
    "chix.sk_spd",
    "chix.no_spd",
    "bacon_spd",
    "p2exbub_spd",
    "mpt_spd",
    "bologna_spd",
    "proc.mts_spd",
    "xtrlean.hamburg_spd",
    "hamb_spd",
    "sand.bf.ham_spd",
    "pork_spd",
    "beef02_spd",
    "tuna_spd",
    "fr.fish.kids_spd",
    "shrimp.ckd_spd",
    "dk.fish_spd",
    "oth.fish_spd",
    "bpt_spd",
    "cold.cereal_spd",
    "cheerio_spd",
    "rz.b.k_spd",
    "c.flk.K_spd",
    "sh.wht_spd",
    "grpnut_spd",
    "total_spd",
    "spec.k_spd",
    "whties_spd",
    "oatmeal.bran_spd",
    "ckd.cer_spd",
    "wh.br_spd",
    "rye.br_spd",
    "dk.br_spd",
    "crax_spd",
    "eng.muff_spd",
    "muff_spd",
    "pancak_spd",
    "br.rice_spd",
    "wh.rice_spd",
    "pasta_spd",
    "tortillas_spd",
    "ff.pot_spd",
    "pot_spd",
    "pot.chip_spd",
    "pizza_spd",
    "bvpt_spd",
    "localcaf_spd",
    "localno_spd",
    "coke_spd",
    "oth.carb_spd",
    "punch_spd",
    "beer_spd",
    "beer.lite_spd",
    "r.wine_spd",
    "w.wine_spd",
    "liq_spd",
    "h2o_spd",
    "herb.tea_spd",
    "tea_spd",
    "decaf_spd",
    "coff_spd",
    "coffdrink_spd",
    "p3exbub_spd",
    "spt_spd",
    "choc_spd",
    "choc.dark_spd",
    "candy_and_nuts_spd",
    "candy_spd",
    "coox.nofat_spd",
    "coox.other_spd",
    "brownie_spd",
    "donut_spd",
    "cake.lofat_spd",
    "cake.other_spd",
    "pie.comm_spd",
    "jam_spd",
    "p.bu_spd",
    "popc.ff.lt_spd",
    "popc_spd",
    "s.roll.lf_spd",
    "s.roll.c_spd",
    "brkfast.bars_spd",
    "power.bar_spd",
    "zone.bar_spd",
    "pretzel_spd",
    "nuts_spd",
    "walnuts_spd",
    "oth.nuts_spd",
    "oat.bran_spd",
    "bran_spd",
    "chow_spd",
    "catsup_spd",
    "splenda_spd",
    "nutrasweet_spd",
    "olive.oil_spd",
    "mayo.d_spd",
    "mayo_spd",
    "o_and_v_spd",
    "dress.nofat_spd",
    "dress.lofat_spd",
    "dress.olive_spd",
    "dress.other_spd",
    "dress.pt_spd",
    "liver_spd",
    "chix.liver_spd",
    "liver.pt_spd",
    "ffh_spd",
    "fb_spd")

select.data <- data.spd %>%
  select (food_items)

food_groups <- data.frame(select.data)


food_groups$promeatffq1 <- hotdog_spd + bacon_spd + chix.dog_spd + proc.mts_spd + bologna_spd
food_groups$redmeatffq1 <- hamb_sp + sand.bf.ham_spd + beef02_spd + pork_spd + xtrlean.hamburg_spd
food_groups$orgmeatffq1 <- chix.liver_spd + liver_spd
food_groups$fishffq1    <- tuna_spd + dk.fish_spd + oth.fish_spd + shrimp.ckd_spd + fr.fish.kids_spd
food_groups$poultffq1   <- chix.sk_spd + chix.no_spd + chix.sand_spd
food_groups$eggsffq1    <- eggs_spd + eggs.omega_spd
food_groups$butterffq1  <- bu
food_groups$margffq1    <- margarine
food_groups$lowdaiffq1  <- skim.kids_spd + yogurt.froz + cot.ch_spd + yog_spd + yog.plain_spd + milk2_spd
food_groups$highdaiffq1 <- milk_spd + cream_spd + cr.ch_spd + ice.cr_spd + oth.ch
food_groups$wineffq1    <- w.wine_spd + r.wine_spd
food_groups$liquorffq1  <- liq_spd
food_groups$beerffq1    <- beer_spd + beer.lite_spd
food_groups$teaffq1     <- herb.tea_spd + tea_spd
food_groups$coffeeffq1  <- decaf_spd + coff_spd
food_groups$fruitffq1   <- raisgrp_spd + orang_spd + prun_spd + ban_spd + cant_spd + apple_spd + straw_spd + blue_spd + peaches_spd + avocado_spd + apricot_spd
food_groups$frujuffq1   <- oth.f.j_spd + a.j_spd + grfrt_spd + o.j.calc_spd + prun.j_spd + o.j_spd
food_groups$cruvegffq1  <- broc_spd + cabb_spd + kale_spd + caul_spd + brusl_spd
food_groups$yelvegffq1  <- carrot.c_spd + carrot.r_spd + yel.sqs_spd + swt.pot_spd
food_groups$tomatoffq1  <- tom_spd + tom.j_spd + tom.s_spd
food_groups$leafvegffq1 <- spin.raw_spd + spin.ckd_spd + ice.let_spd + rom.let_spd
food_groups$legumeffq1  <- tofu_spd + st.beans_spd + peas_spd + beans_spd + soymilk.fort_spd
food_groups$othvegffq1  <- corn_spd + mix_veg + zuke_spd + celery_spd + peppers_spd + onions_spd + onions1_spd
food_groups$potatoffq1  <- pot_spd
food_groups$frenchffq1  <- ff.pot_spd
food_groups$wholegffq1  <- br.rice_spd + oat.bran_spd + ckd.cer_spd + oatmeal.bran_spd + rye.br_spd + dk.br_spd
food_groups$refingffq1  <- wh.br_spd + wh.rice_spd + eng.muff_spd + muff_spd + pasta_spd + pancak_spd + tortillas
food_groups$pizzaffq1   <- pizza_spd
food_groups$sugdrkffq1  <- punch_spd + oth.carb + coke
food_groups$lowdrkffq1  <- localcaf_spd + localno_spd 
food_groups$snackffq1   <- pot.chip + pretzel_spd + popc.ff.lt_spd + popc + crax_spd
food_groups$nutsffq1    <- p.bu_spd + nuts_spd + oth.nuts_spd + walnuts_spd
food_groups$mayoffq1    <- mayo_spd + mayo.d_spd
food_groups$dressffq1   <- o_and_v_spd
food_groups$crmsoupffq1 <- chow_spd
food_groups$sweetsffq1  <- candy_spd + candy_and_nuts_spd + coox.nofat_spd + coox.other_spd + brownie_spd + donut_spd + cake.other_spd + choc_spd + choc.dark_spd + jam_spd + s.roll.lf_spd + cake.lofat_spd + pie.comm_spd
food_groups$condimffq1  <- cof.wht_spd + catsup_spd + salsa_spd
 

food_groups <- food_groups %>%
  select(-food_items)
